version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourPassword123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  yourapp:
    build:
      context: ./UniTaskAssignment
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sqlserver
